server:
  # 端口
  port: 8085

spring:
  # 数据源配置
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://127.0.0.1:5236
    username: USER_DBTEST
    password: 123456789
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DmDialect
    hibernate:
      ddl:
        auto: none

# Mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis 数据返回类型别名(默认别名是类名)
  type-aliases-package: com.xxx.server.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      table-prefix: ENETCMS_
  configuration-properties:
    prefix: ENETCMS_

## Mybatis SQL 打印(方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.xxx.server.mapper: debug
jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: yeb-secret
  # JWT的超期限时间(60*60*24)
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer
website:
  # 每页显示多少个
  page_num: 1